### ISSUE TITLE
Does not work in a profile

### ISSUE THREAD

**Issue by LongJohn-Silver** [null-dev/firefox-profile-switcher#6]
I have two profiles on Firefox, I installed the extension in my main profile called "Profile 01", I installed the connector dowbloading here, also. Then I launched the "Profile 02" and installed the extension.

When I have only the Profile 02 active and I try to open Profile 01 through the extension it does nothing.

**Comment by MattHardcastle** [comment]
@LongJohn-Silver, this issues sound like [an issue](firefox-profile-switcher-connector) I opened on the firefox-profile-switcher-connector repo. What platform are you using?

**Comment by LongJohn-Silver** [comment]
@MattHardcastle I am using a fork of Ubuntu, so I guess it is a OS independent bug.

**Comment by null-dev** [comment]
This should be fixed in the latest version of the extension. Make sure to also update the connector if the extension asks you. Please re-open the issue if you come across the bug again.

**Comment by jsdev63** [comment]
It's same for me.
How can I solve this?
I just installed the latest version?

**Comment by LongJohn-Silver** [comment]
@jsdev63 Same, I still have the same bug. @null-dev

**Comment by null-dev** [comment]
@LongJohn-Silver Alright, I've released another version along with another connector to attempt to solve this issue. Please also try the new "Window focus workaround" setting and see if that fixes the issue.

If nothing works, can you perform the following?

1. Run this command: `touch ~/.local/share/firefoxprofileswitcher/DEBUG` and then restarting your browser? This will enable debug logging for the extension.
2. Try launching "Profile 01" from "Profile 02" again.
3. Send me the log found here: `~/.local/share/firefoxprofileswitcher/log.txt`. You can do this by dragging and dropping the log file into the comment editor window.

**Comment by LongJohn-Silver** [comment]
@null-dev, still not working, also, I don't know if this is related to FFProfileSwitcher or what, but I install the .deb using Eddy and it is the only application so far that when I open it with it, it tells me to downgrade instead of to update. Mentioning just in case, here's the log: [log.txt](https://github.com/null-dev/firefox-profile-switcher/files/6818677/log.txt)

**Comment by null-dev** [comment]
Actually, I can now reproduce this occasionally too. I think it's because the method the program uses to talk between open browser profiles is unreliable. Unfortunately it seems it's going to be a pain to fix, but I'll keep looking. I'll also have a look into the issue with the .deb file

**Comment by null-dev** [comment]
I've pushed out a new update that attempts to fix this, if it's still happening, please let me know!
